name: Publish packages to npmjs on renovate[bot] automerge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  tests:
    if: github.event.pull_request.merged == true && github.event.sender.login == 'renovate[bot]'
    uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests

  build:
    if: github.event.pull_request.merged == true && github.event.sender.login == 'renovate[bot]'
    needs: [tests]  # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Configure git before publish
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "joel.charles91@gmail.com"

      - run: pnpm run release:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
