on:
  - pull_request

jobs:
  cache-and-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16", "18"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - uses: oven-sh/setup-bun@v1
        # At the moment of writing:
        # - bun does not support Windows
        # - bun fails to install some dependencies on macos with node@18
        # if: matrix.os != 'windows-latest' && !(matrix.os == 'macos-latest' && matrix.node == '18')
        if: matrix.os != 'windows-latest'
        name: Install bun
        with:
          bun-version: "1.0.4"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: TurboRepo Remote Cache Server
        uses: trappar/turborepo-remote-cache-gh-action@main
        env:
          TURBO_CACHE_USE_TMP_FOLDER: true
        with:
          storage-provider: local
          storage-path: bati
          team-id: bati
          port: 9999

      - name: Run tests
        run: pnpm run -r test

      - name: Run e2e tests
        run: pnpm run --filter=tests test:e2e
